name: container

on:
  push:
    tags:
    - "v*.*.*"
    - "v*.*"
  workflow_dispatch:

jobs:
  build:
    uses: https://git.k8s.lan/actions/container/.gitea/workflows/container.yaml@v1
    secrets: inherit
